### ISSUE TITLE
This seems to be KO on Windows

### ISSUE THREAD

**Issue by amoutonbrady** [galvez/universify-test#1]
Hey, ran it on my setup and it didn't seem to work.
It's mostly related to Windows.

Node and npm version : 

```bash
universify-test(main)> node -v
v16.13.2
universify-test(main)> npm -v
8.1.2
```

OS : Windows 11 (no WSL)

Hope this helps!

**Comment by galvez** [comment]
Hey, thanks for trying this. Can you share the error message, if any?

**Comment by amoutonbrady** [comment]
Sorry for the delay. I sure can, don't know why I didn't include it in the first run...

```bash
universify-test(main)> npx uni app
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:371:5)
    at defaultResolve (node:internal/modules/esm/resolve:1016:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ESMLoader.import (node:internal/modules/esm/loader:276:22)
    at importModuleDynamically (node:internal/modules/esm/translators:111:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at resolveInit (file:///C:/Users/amout/Lab/universify-test/node_modules/universify/utils.mjs:9:19)
    at file:///C:/Users/amout/Lab/universify-test/node_modules/universify/index.mjs:7:28
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

**Comment by galvez** [comment]
It seems to be a problem with your Node version. Universify is Node v16+ only.
